### ISSUE TITLE
Underlining tabs

### ISSUE THREAD

**Issue by LeCyberDucky** [LukasKalbertodt/bunt#25]
Hey there! 

I have a string `header` with this content: `"    \tSnippet name:                \t  Source file:"` (note, that GitHub doesn't really display all the contained whitespace). I'm trying to print this string underlined: `bunt::println!("{[underline]}", header);`, but the underlining stops at the tabs. Is this intended behavior? If so, what would be the best workaround here? My output currently looks like this: 

![image](https://user-images.githubusercontent.com/19520383/133935932-4f50ef7e-665c-499d-ad9c-6848b5c030a3.png)

As a side note, the line `bunt::println!("{[underline]}", header);` gives me an error in VS Code with Rust-Analyzer: 

```
expected none or () delimited group, but found different token tree (note: do not use the macros from `bunt-macros` directly, but only through `bunt`) 
rust-analyzer(macro-error)
```

Is this something that I should post an issue about, or would it rather belong in the Rust-Analyzer repository?

**Comment by LukasKalbertodt** [comment]
Hi there!

The issue is not with `bunt` or even `termcolor`, but it's a terminal rendering issue. I just tried this code:

```rust
let header =  "   \tSnippet name:   \t Source file:";
bunt::println!("{[underline]}", header);
```

And I see the same problem with the tabs not being underlined with the default Ubuntu terminal application. But inspecting what is emitted by the application with `cargo run | hexdump -C` shows this:

```
00000000  1b 5b 30 6d 1b 5b 34 6d  20 20 20 09 53 6e 69 70  |.[0m.[4m   .Snip|
...
```

This is an ANSI control "reset" (`\x1b[0m`) and an underline sequence (`\x1b[4m`) followed by three spaces and then a tab character. So the emitted sequences are fine. So yeah, nothing we can do here. 

As a workaround you could use something like the underscore character to draw explicit underlines. But then you could also use underlined spaces. But for drawing tables you probably want to use box drawing characters: https://en.wikipedia.org/wiki/Box-drawing_character. But either way, you have to code your own "tab" logic somehow. Which might be better anyway because relying on a specific tab width for terminals is also probably not a great idea. I hope this helps!

> As a side note [...]

Yeah, I'm aware of that. There is this issue about it: https://github.com/LukasKalbertodt/bunt/issues/20
I'm kind of annoyed by it too and might reconsider changing `bunt` to workaround this problem as it seems quite hard in rust analyzer to fix.

**Comment by LeCyberDucky** [comment]
Alright, thanks for the quick and detailed response! 

Ich wünsche noch einen schönen Abend =)
