### ISSUE TITLE
ANSI 256 as #3-tuples

### ISSUE THREAD

**Issue by nojhan** [LukasKalbertodt/bunt#26]
Docs says "there is currently no syntax for Color::Ansi256 because I couldn’t come up with a nice syntax and I never used these ansi colors…)". I do need those ones.

What about just using a `#123` syntax? If RGB should always be 6-tuple strings, then there is no ambiguity with ANSI's 256 3-tuple.

The meaning should be straigthforward, but may collides in users mind with CSS' short 3-tuple RGB (for which `#fff` is a valid shortcut for `#ffffff`).

Alternatively, any other prefix may be used, like `@`, which reminds the A of ANSI.

**Comment by LukasKalbertodt** [comment]
Just so I don't misunderstand: the `123` in your example would be a decimal number between `#0` and `#255`? Or is it three separate components as you said "3-tuple"? That wouldn't make a lot of sense according to [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit), right? Because (a) how to split 8 bit into 3 components, and (b) the individual components wouldn't really have a meaning on their own like in RGB hex codes, right?

I also immediately thought it would cause confusion with people used to short hex codes in CSS. Thus I would prefer another prefix. Apart from `@`, `$`, `%`, `~` would also be fine I guess. But yeah, why not `@` :shrug:

**Comment by nojhan** [comment]
Yes, I was thinking of "three digits", between 001 and 255. That would be
***@***.***", ***@***.***" ***@***.******@***.***".

Le dim. 13 nov. 2022 à 10:01, Lukas Kalbertodt ***@***.***> a
écrit :

**Comment by LukasKalbertodt** [comment]
Woopsie! Because you replied via mail, GitHub detected those the things around `@` as email addresses and censored them. Could you write that again via GitHub UI? ^_^

**Comment by nojhan** [comment]
Now that's a fun behavior.

I was thinking of "three digits", between 001 and 255. That would be "@001", "@012", "@123", "@255", etc.

**Comment by LukasKalbertodt** [comment]
Any specific reason you would force users to add leading 0s? The syntax would be unambiguous even for `@12`, right?

**Comment by nojhan** [comment]
Looked more consistent to me, comparing with RGB hex. But it's probably better to just use short numbers, given that all docs on ANSI present them without leading zeros.

**Comment by LukasKalbertodt** [comment]
Okay yeah, I would also not force leading zeros I think.

I guess then we have a plan.  Do you wanna give it a try and prepare a PR? Otherwise I might do it in the near future -- no promises tho!

**Comment by nojhan** [comment]
I still have to learn Rust and use it to port a project (using bunt ;), so it's going to take some time for me as well.

**Comment by LukasKalbertodt** [comment]
Then I will have a stab at it I guess! I hope you're enjoying Rust so far ;-)

**Comment by LukasKalbertodt** [comment]
Fixed in fc63556d96c89fee12d3e12a19f2ced35519ddd2 and released as v0.2.8
